# Generated by Django 6.0.7 on 2026-08-11 12:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_user_id'),
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, default='', help_text='Optional user note (control characters stripped).', max_length=280)),
                ('sort_order', models.IntegerField(default=0, help_text="Display order within the account's watchlist.")),
                ('account', models.ForeignKey(help_text='The account that owns this watchlist entry.', on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entries', to='accounts.account')),
                ('instrument', models.ForeignKey(help_text='The instrument tracked on the watchlist.', on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entries', to='market_data.instrument')),
            ],
            options={
                'verbose_name': 'Watchlist Entry',
                'verbose_name_plural': 'Watchlist Entries',
                'db_table': 'watchlist_watchlistentry',
                'indexes': [models.Index(fields=['account', 'sort_order'], name='idx_watchlist_account_sort')],
                'unique_together': {('account', 'instrument')},
            },
        ),
    ]
