# Generated by Django 6.0.7 on 2026-07-31 17:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument_token",
                    models.BigIntegerField(
                        help_text="Exchange-assigned numeric token.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        db_index=True,
                        help_text="Exchange code (e.g. NSE, BSE).",
                        max_length=10,
                    ),
                ),
                (
                    "tradingsymbol",
                    models.CharField(
                        help_text="Exchange-listed trading symbol (e.g. RELIANCE).",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable company name.",
                        max_length=255,
                    ),
                ),
                (
                    "segment",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Market segment (e.g. EQUITY, FNO).",
                        max_length=50,
                    ),
                ),
                (
                    "lot_size",
                    models.IntegerField(default=1, help_text="Minimum trade quantity."),
                ),
                (
                    "tick_size",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.05"),
                        help_text="Minimum price increment.",
                        max_digits=20,
                    ),
                ),
                (
                    "instrument_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Instrument category (e.g. EQ, FUT, OPT).",
                        max_length=20,
                    ),
                ),
                (
                    "expiry",
                    models.DateTimeField(
                        blank=True,
                        help_text="Derivative contract expiry (UTC).",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this instrument is currently tradeable.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrument",
                "verbose_name_plural": "Instruments",
                "db_table": "market_data_instrument",
                "indexes": [
                    models.Index(
                        fields=["exchange", "tradingsymbol"],
                        name="idx_instrument_exchange_symbol",
                    ),
                    models.Index(fields=["is_active"], name="idx_instrument_active"),
                ],
                "unique_together": {("exchange", "tradingsymbol")},
            },
        ),
        migrations.CreateModel(
            name="Candle",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "timeframe",
                    models.CharField(
                        db_index=True,
                        help_text="Aggregation interval (e.g. 1min, 15min, 1D).",
                        max_length=10,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, help_text="Candle open time (UTC)."
                    ),
                ),
                (
                    "open",
                    models.DecimalField(
                        decimal_places=4, help_text="Opening price.", max_digits=20
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Highest price during the interval.",
                        max_digits=20,
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Lowest price during the interval.",
                        max_digits=20,
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        decimal_places=4, help_text="Closing price.", max_digits=20
                    ),
                ),
                ("volume", models.BigIntegerField(help_text="Total traded volume.")),
                (
                    "instrument",
                    models.ForeignKey(
                        help_text="The instrument this candle belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candles",
                        to="market_data.instrument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candle",
                "verbose_name_plural": "Candles",
                "db_table": "market_data_candle",
                "indexes": [
                    models.Index(
                        fields=["instrument", "timeframe", "-timestamp"],
                        name="idx_candle_lookup",
                    )
                ],
                "unique_together": {("instrument", "timeframe", "timestamp")},
            },
        ),
    ]
