# Generated by Django 5.0.14 on 2026-08-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("zerodha", "Zerodha Kite Connect"),
                            ("csv", "CSV Import"),
                            ("yfinance", "yfinance"),
                        ],
                        db_index=True,
                        help_text="Data source for this sync run.",
                        max_length=20,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        db_index=True,
                        help_text="Trading symbol (e.g. RELIANCE).",
                        max_length=100,
                    ),
                ),
                (
                    "timeframe",
                    models.CharField(
                        db_index=True,
                        help_text="Aggregation interval (e.g. 1D, 1min).",
                        max_length=10,
                    ),
                ),
                (
                    "range_start",
                    models.DateTimeField(
                        db_index=True, help_text="Start of the date range (UTC)."
                    ),
                ),
                (
                    "range_end",
                    models.DateTimeField(
                        db_index=True, help_text="End of the date range (UTC)."
                    ),
                ),
                (
                    "rows_written",
                    models.IntegerField(
                        default=0, help_text="Number of candle rows written/updated."
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the sync run started."
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, help_text="When the sync run finished.", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("PARTIAL", "Partial"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Current status of the sync run.",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if the run failed.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Run",
                "verbose_name_plural": "Sync Runs",
                "db_table": "market_data_syncrun",
                "indexes": [
                    models.Index(
                        fields=["source", "symbol", "timeframe"],
                        name="idx_syncrun_source_symbol_tf",
                    ),
                    models.Index(
                        fields=["status", "started_at"],
                        name="idx_syncrun_status_started",
                    ),
                ],
            },
        ),
    ]
