# Generated by Django 5.0.14 on 2026-09-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_data", "0002_syncrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndexConstituent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "index_name",
                    models.CharField(
                        db_index=True,
                        default="NIFTY200",
                        help_text="Index this row belongs to (e.g. NIFTY200).",
                        max_length=20,
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        default="NSE",
                        help_text="Exchange code the constituent trades on.",
                        max_length=10,
                    ),
                ),
                (
                    "tradingsymbol",
                    models.CharField(
                        help_text="Exchange-listed trading symbol (e.g. RELIANCE).",
                        max_length=100,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable company name from the index CSV.",
                        max_length=255,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Industry classification from the index CSV.",
                        max_length=100,
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        blank=True,
                        default="EQ",
                        help_text="Security series (e.g. EQ).",
                        max_length=10,
                    ),
                ),
                (
                    "isin_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ISIN code from the index CSV.",
                        max_length=20,
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="Position in the published CSV (0-based)."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this symbol is currently a member of the index.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Index Constituent",
                "verbose_name_plural": "Index Constituents",
                "db_table": "market_data_indexconstituent",
                "indexes": [
                    models.Index(
                        fields=["index_name", "is_active"],
                        name="idx_indexconstituent_active",
                    ),
                    models.Index(
                        fields=["index_name", "is_active", "sort_order"],
                        name="idx_indexconstituent_universe",
                    ),
                ],
                "unique_together": {("index_name", "exchange", "tradingsymbol")},
            },
        ),
    ]
