# Generated by Django 5.0.14 on 2026-08-19 15:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DashboardHomeSummary",
            fields=[
                ("projection_version", models.IntegerField(default=0)),
                ("projection_updated_at", models.DateTimeField(blank=True, null=True)),
                ("last_event_id", models.UUIDField(blank=True, null=True)),
                ("last_event_version", models.IntegerField(default=0)),
                ("account_id", models.UUIDField(primary_key=True, serialize=False)),
                ("open_positions_count", models.IntegerField(default=0)),
                ("open_orders_count", models.IntegerField(default=0)),
                (
                    "today_realized_pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "today_unrealized_pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("active_alerts_count", models.IntegerField(default=0)),
                (
                    "broker_connection_status",
                    models.CharField(default="disconnected", max_length=20),
                ),
                (
                    "market_session_status",
                    models.CharField(default="closed", max_length=20),
                ),
            ],
            options={
                "db_table": "dashboard_homesummary",
            },
        ),
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                ("export_id", models.UUIDField(primary_key=True, serialize=False)),
                ("account_id", models.UUIDField(db_index=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("format", models.CharField(max_length=10)),
                ("file_url", models.URLField(blank=True, null=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "dashboard_exportjob",
            },
        ),
        migrations.CreateModel(
            name="Holding",
            fields=[
                ("projection_version", models.IntegerField(default=0)),
                ("projection_updated_at", models.DateTimeField(blank=True, null=True)),
                ("last_event_id", models.UUIDField(blank=True, null=True)),
                ("last_event_version", models.IntegerField(default=0)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("account_id", models.UUIDField(db_index=True)),
                ("symbol", models.CharField(max_length=20)),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=20)),
                ("avg_cost", models.DecimalField(decimal_places=8, max_digits=20)),
                ("cost_basis", models.DecimalField(decimal_places=8, max_digits=20)),
                ("opened_at", models.DateTimeField()),
            ],
            options={
                "db_table": "dashboard_holding",
            },
        ),
        migrations.CreateModel(
            name="OrderSnapshot",
            fields=[
                ("projection_version", models.IntegerField(default=0)),
                ("projection_updated_at", models.DateTimeField(blank=True, null=True)),
                ("last_event_id", models.UUIDField(blank=True, null=True)),
                ("last_event_version", models.IntegerField(default=0)),
                ("order_id", models.UUIDField(primary_key=True, serialize=False)),
                ("account_id", models.UUIDField(db_index=True)),
                ("symbol", models.CharField(max_length=20)),
                ("side", models.CharField(max_length=4)),
                ("order_type", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=20)),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "filled_quantity",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "avg_fill_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "limit_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                ("placed_at", models.DateTimeField()),
            ],
            options={
                "db_table": "dashboard_ordersnapshot",
            },
        ),
        migrations.CreateModel(
            name="PerformanceSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("account_id", models.UUIDField(db_index=True)),
                ("period", models.CharField(max_length=10)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "win_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "avg_win",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "avg_loss",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "profit_factor",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "expectancy",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "sharpe_like_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("total_trades", models.IntegerField(default=0)),
                ("winning_trades", models.IntegerField(default=0)),
                ("losing_trades", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "dashboard_performance_snapshot",
            },
        ),
        migrations.CreateModel(
            name="PnLDailyRollup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("account_id", models.UUIDField(db_index=True)),
                ("trading_date", models.DateField()),
                (
                    "realized_pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "total_pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "cumulative_pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "peak_cumulative_pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "drawdown_pct",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
            ],
            options={
                "db_table": "dashboard_pnl_daily_rollup",
            },
        ),
        migrations.CreateModel(
            name="PnLSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("account_id", models.UUIDField(db_index=True)),
                ("snapshot_at", models.DateTimeField()),
                (
                    "realized_pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "total_pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "cumulative_pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "peak_cumulative_pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "drawdown_pct",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("last_event_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "dashboard_pnl_snapshot",
            },
        ),
        migrations.CreateModel(
            name="PositionSnapshot",
            fields=[
                ("projection_version", models.IntegerField(default=0)),
                ("projection_updated_at", models.DateTimeField(blank=True, null=True)),
                ("last_event_id", models.UUIDField(blank=True, null=True)),
                ("last_event_version", models.IntegerField(default=0)),
                ("position_id", models.UUIDField(primary_key=True, serialize=False)),
                ("account_id", models.UUIDField(db_index=True)),
                ("symbol", models.CharField(max_length=20)),
                ("side", models.CharField(max_length=4)),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=20)),
                ("entry_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("is_open", models.BooleanField(default=True)),
                ("opened_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "dashboard_positionsnapshot",
            },
        ),
        migrations.CreateModel(
            name="RiskAlertProjection",
            fields=[
                (
                    "alert_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("account_id", models.UUIDField(db_index=True)),
                ("alert_type", models.CharField(max_length=50)),
                ("severity", models.CharField(max_length=20)),
                ("message", models.TextField()),
                ("raised_at", models.DateTimeField()),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("last_event_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "dashboard_risk_alert_projection",
            },
        ),
        migrations.CreateModel(
            name="RiskMetricSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("account_id", models.UUIDField(db_index=True)),
                ("snapshot_at", models.DateTimeField()),
                (
                    "total_exposure",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "largest_position_pct",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "sector_concentration_pct",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "leverage_ratio",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
            ],
            options={
                "db_table": "dashboard_risk_metric_snapshot",
            },
        ),
        migrations.CreateModel(
            name="TradeRecord",
            fields=[
                ("projection_version", models.IntegerField(default=0)),
                ("projection_updated_at", models.DateTimeField(blank=True, null=True)),
                ("last_event_id", models.UUIDField(blank=True, null=True)),
                ("last_event_version", models.IntegerField(default=0)),
                ("trade_id", models.UUIDField(primary_key=True, serialize=False)),
                ("account_id", models.UUIDField(db_index=True)),
                ("symbol", models.CharField(max_length=20)),
                ("side", models.CharField(max_length=4)),
                ("entry_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("exit_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=20)),
                ("realized_pnl", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "realized_pnl_pct",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                ("opened_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField()),
                ("holding_period_seconds", models.IntegerField()),
            ],
            options={
                "db_table": "dashboard_traderecord",
            },
        ),
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.UUIDField(db_index=True)),
                ("projector", models.CharField(max_length=255)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "dashboard_eventlog",
                "indexes": [
                    models.Index(
                        fields=["event_id", "projector"],
                        name="dashboard_e_event_i_ddbdb7_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="eventlog",
            constraint=models.UniqueConstraint(
                fields=("event_id", "projector"),
                name="uq_dashboard_eventlog_event_projector",
            ),
        ),
        migrations.AddIndex(
            model_name="exportjob",
            index=models.Index(
                fields=["account_id", "status"], name="dashboard_e_account_15c395_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="holding",
            index=models.Index(
                fields=["account_id", "quantity"], name="idx_holding_account_qty"
            ),
        ),
        migrations.AddConstraint(
            model_name="holding",
            constraint=models.UniqueConstraint(
                fields=("account_id", "symbol"), name="uq_holding_account_symbol"
            ),
        ),
        migrations.AddIndex(
            model_name="ordersnapshot",
            index=models.Index(
                fields=["account_id", "status", "placed_at"],
                name="idx_orders_acct_status_placed",
            ),
        ),
        migrations.AddIndex(
            model_name="ordersnapshot",
            index=models.Index(
                fields=["account_id", "symbol", "placed_at"],
                name="dashboard_o_account_544096_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="performancesnapshot",
            constraint=models.UniqueConstraint(
                fields=("account_id", "period"), name="uq_performance_account_period"
            ),
        ),
        migrations.AddConstraint(
            model_name="pnldailyrollup",
            constraint=models.UniqueConstraint(
                fields=("account_id", "trading_date"), name="uq_pnl_daily_account_date"
            ),
        ),
        migrations.AddIndex(
            model_name="pnlsnapshot",
            index=models.Index(
                fields=["account_id", "-snapshot_at"],
                name="dashboard_p_account_c43442_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="positionsnapshot",
            index=models.Index(
                fields=["account_id", "is_open"], name="idx_positions_account_open"
            ),
        ),
        migrations.AddIndex(
            model_name="positionsnapshot",
            index=models.Index(
                fields=["account_id", "symbol"], name="dashboard_p_account_419259_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riskalertprojection",
            index=models.Index(
                fields=["account_id", "-raised_at"],
                name="dashboard_r_account_7babfd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="riskmetricsnapshot",
            index=models.Index(
                fields=["account_id", "-snapshot_at"],
                name="dashboard_r_account_decd27_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="traderecord",
            index=models.Index(
                fields=["account_id", "closed_at"], name="idx_trades_account_closed"
            ),
        ),
        migrations.AddIndex(
            model_name="traderecord",
            index=models.Index(
                fields=["account_id", "symbol", "closed_at"],
                name="dashboard_t_account_bd556b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="traderecord",
            index=models.Index(
                fields=["account_id", "realized_pnl"],
                name="dashboard_t_account_874c26_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="traderecord",
            constraint=models.UniqueConstraint(
                fields=("last_event_id",), name="uq_traderecord_last_event_id"
            ),
        ),
    ]
