# Generated by Django 5.2.16 on 2026-08-05 09:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_apikey_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4, not auto-increment).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC datetime when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC datetime when this record was last modified.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True when this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='UTC datetime when this record was soft-deleted.', null=True)),
                ('symbol', models.CharField(db_index=True, max_length=100)),
                ('timeframe', models.CharField(blank=True, default='', max_length=20)),
                ('range_start', models.DateTimeField()),
                ('range_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('last_processed_snapshot_id', models.UUIDField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.OneToOneField(help_text='Dedicated, isolated account that owns every record of this run.', on_delete=django.db.models.deletion.CASCADE, related_name='backtest_run', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Backtest Run',
                'verbose_name_plural': 'Backtest Runs',
                'db_table': 'backtesting_backtestrun',
                'indexes': [models.Index(fields=['symbol', 'range_start', 'range_end'], name='idx_bt_symbol_range'), models.Index(fields=['status'], name='idx_bt_status')],
            },
        ),
    ]
