# Generated by Django 5.0.14 on 2026-09-25 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backtesting", "0002_backtestrun_benchmark_return_and_more"),
        ("strategy_registry", "0002_alter_tradingstrategy_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtestrun",
            name="strategy",
            field=models.ForeignKey(
                blank=True,
                help_text="Strategy this run backtests. When set, replay is isolated to the strategy's designed rules (see strategy-registry rule map).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="backtest_runs",
                to="strategy_registry.tradingstrategy",
            ),
        ),
    ]
