# Generated by Django 6.0.7 on 2026-08-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_recommendation_and_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='correlation_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='provider',
            field=models.CharField(db_index=True, default='fallback', max_length=50),
        ),
    ]
