# Generated by Django 5.0.14 on 2026-08-19 07:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_rename_recommendat_symbol_ea83d2_idx_recommendat_symbol_9d6ca0_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recommendation',
            new_name='recommendat_symbol_9d6ca0_idx',
            old_name='recommendat_symbol_ea83d2_idx',
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC datetime when this record was created.'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='UTC datetime when this record was soft-deleted.', null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4, not auto-increment).', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='True when this record has been soft-deleted.'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='UTC datetime when this record was last modified.'),
        ),
        migrations.AlterField(
            model_name='recommendationstatushistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC datetime when this record was created.'),
        ),
        migrations.AlterField(
            model_name='recommendationstatushistory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='UTC datetime when this record was soft-deleted.', null=True),
        ),
        migrations.AlterField(
            model_name='recommendationstatushistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4, not auto-increment).', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recommendationstatushistory',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='True when this record has been soft-deleted.'),
        ),
        migrations.AlterField(
            model_name='recommendationstatushistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='UTC datetime when this record was last modified.'),
        ),
    ]
