# Generated by Django 6.0.7 on 2026-07-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pineoutput',
            new_name='intelligenc_symbol_ccaa8a_idx',
            old_name='intelligen_symbol_0e1afc_idx',
        ),
        migrations.RenameIndex(
            model_name='pineoutput',
            new_name='intelligenc_timefra_4fa9ab_idx',
            old_name='intelligen_timefra_90f52b_idx',
        ),
        migrations.AlterField(
            model_name='pineoutput',
            name='detected_timestamp',
            field=models.DateTimeField(help_text='When the indicator was calculated by Pine Script'),
        ),
        migrations.AlterField(
            model_name='pineoutput',
            name='values',
            field=models.JSONField(help_text="Indicator values as key-value pairs, e.g. {'rsi_14': 62.5, 'macd': 1.23}"),
        ),
        migrations.AlterModelTable(
            name='pineoutput',
            table=None,
        ),
    ]
