# Generated by Django 6.0.7 on 2026-08-04 16:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4, not auto-increment).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC datetime when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC datetime when this record was last modified.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True when this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='UTC datetime when this record was soft-deleted.', null=True)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('account_id', models.UUIDField(db_index=True)),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('side', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('stop_loss', models.DecimalField(decimal_places=8, max_digits=20)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('causation_id', models.UUIDField(blank=True, null=True)),
                ('risk_approved_event_id', models.UUIDField(unique=True)),
                ('rule_id', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(default='', max_length=50)),
                ('status', models.CharField(db_index=True, default='RECEIVED', max_length=40)),
                ('reason_message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Execution Request',
                'verbose_name_plural': 'Execution Requests',
                'db_table': 'execution_executionrequest',
                'indexes': [models.Index(fields=['account_id', 'symbol'], name='idx_exec_req_account_symbol')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4, not auto-increment).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC datetime when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC datetime when this record was last modified.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True when this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='UTC datetime when this record was soft-deleted.', null=True)),
                ('account_id', models.UUIDField(db_index=True)),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('side', models.CharField(max_length=10)),
                ('order_type', models.CharField(default='market', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.CharField(db_index=True, default='CREATED', max_length=20)),
                ('filled_quantity', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('avg_fill_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('broker_order_ref', models.CharField(blank=True, max_length=64, null=True)),
                ('broker_name', models.CharField(default='paper', max_length=30)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('stop_loss', models.DecimalField(decimal_places=8, max_digits=20)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('causation_id', models.UUIDField(blank=True, null=True)),
                ('execution_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='execution.executionrequest')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'execution_order',
            },
        ),
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4, not auto-increment).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC datetime when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC datetime when this record was last modified.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True when this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='UTC datetime when this record was soft-deleted.', null=True)),
                ('sequence', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('occurred_at', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fills', to='execution.order')),
            ],
            options={
                'verbose_name': 'Fill',
                'verbose_name_plural': 'Fills',
                'db_table': 'execution_fill',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['account_id', 'status'], name='idx_exec_order_account_status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['account_id', 'symbol'], name='idx_exec_order_account_symbol'),
        ),
        migrations.AddConstraint(
            model_name='fill',
            constraint=models.UniqueConstraint(fields=('order', 'sequence'), name='uq_execution_fill_order_sequence'),
        ),
    ]
