# Generated by Django 6.0.7 on 2026-08-02 17:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_apikey_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCapitalState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4, not auto-increment).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC datetime when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC datetime when this record was last modified.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True when this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='UTC datetime when this record was soft-deleted.', null=True)),
                ('cash', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('margin_used', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('equity', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('available_capital', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('realized_pnl_today', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('unrealized_pnl_today', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capital_state', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Account Capital State',
                'verbose_name_plural': 'Account Capital States',
                'db_table': 'portfolio_accountcapitalstate',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4, not auto-increment).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC datetime when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC datetime when this record was last modified.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True when this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='UTC datetime when this record was soft-deleted.', null=True)),
                ('account_id', models.UUIDField(db_index=True)),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('side', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('avg_entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('opened_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'db_table': 'portfolio_position',
                'indexes': [models.Index(fields=['account_id', 'opened_at'], name='idx_port_pos_account_opened')],
                'constraints': [models.UniqueConstraint(fields=('account_id', 'symbol'), name='uq_portfolio_position_account_symbol')],
            },
        ),
        migrations.CreateModel(
            name='PositionFillExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4, not auto-increment).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC datetime when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC datetime when this record was last modified.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True when this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='UTC datetime when this record was soft-deleted.', null=True)),
                ('source_fill_id', models.UUIDField(unique=True)),
                ('account_id', models.UUIDField(db_index=True)),
                ('symbol', models.CharField(max_length=50)),
                ('side', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('applied_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Position Fill Execution',
                'verbose_name_plural': 'Position Fill Executions',
                'db_table': 'portfolio_positionfillexecution',
                'indexes': [models.Index(fields=['account_id', 'symbol'], name='idx_port_fill_account_symbol')],
            },
        ),
    ]
