# Generated by Django 6.0.7 on 2026-08-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Stop-loss price captured at position open time (nullable for positions opened before this batch shipped). Not updated on same-direction add-on fills (pyramiding).', max_digits=20, null=True),
        ),
    ]
