# Generated by Django 5.2.16 on 2026-08-17 07:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4, not auto-increment).",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="UTC datetime when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="UTC datetime when this record was last modified.",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True when this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="UTC datetime when this record was soft-deleted.",
                        null=True,
                    ),
                ),
                (
                    "provider_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Provider-side article id (Marketaux 'uuid'); empty when absent.",
                        max_length=64,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        db_index=True,
                        help_text="Publication/feed name (e.g. 'Reuters').",
                        max_length=128,
                    ),
                ),
                ("headline", models.TextField(help_text="Article title.")),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Article summary/body snippet when the provider returns one.",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        db_index=True,
                        help_text="Canonical article URL — part of the (source, url) dedup key.",
                        max_length=2048,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When the provider says the article was published.",
                    ),
                ),
                (
                    "ingested_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When TradeVision stored this row.",
                    ),
                ),
                (
                    "symbols",
                    models.JSONField(
                        default=list,
                        help_text="Symbols the provider identified in the article (e.g. ['RELIANCE']).",
                    ),
                ),
                (
                    "sentiment_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Provider-supplied sentiment in [-1, 1]; NULL = provider returned none.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "sentiment_label",
                    models.CharField(
                        blank=True,
                        help_text="NULL in this batch — no provider returns a label; not hand-rolled.",
                        max_length=16,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "News Item",
                "verbose_name_plural": "News Items",
                "db_table": "news_feed_newsitem",
                "indexes": [
                    models.Index(fields=["published_at"], name="newsitem_published_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "url"), name="uniq_newsitem_source_url"
                    )
                ],
            },
        ),
    ]
