# Generated by Django 6.0.7 on 2026-08-15 06:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MacroObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4, not auto-increment).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC datetime when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC datetime when this record was last modified.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True when this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='UTC datetime when this record was soft-deleted.', null=True)),
                ('provider', models.CharField(max_length=32)),
                ('series_id', models.CharField(db_index=True, max_length=32)),
                ('observed_at', models.DateField()),
                ('published_at', models.DateTimeField()),
                ('value', models.DecimalField(blank=True, decimal_places=6, help_text="NULL = known missing (FRED '.'), never zero.", max_digits=20, null=True)),
            ],
            options={
                'verbose_name': 'Macro Observation',
                'verbose_name_plural': 'Macro Observations',
                'db_table': 'macro_context_macroobservation',
                'indexes': [models.Index(fields=['series_id', 'observed_at', 'published_at'], name='macro_obs_pit_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'series_id', 'observed_at', 'published_at'), name='uniq_macro_observation_vintage')],
            },
        ),
    ]
