# Generated by Django 6.0.7 on 2026-08-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rule_engine", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ruleexecution",
            name="trigger_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
