# Generated by Django 6.0.7 on 2026-08-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rule_engine", "0002_alter_ruleexecution_trigger_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="ruleconfig",
            name="validated_regimes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-regime go/no-go verdict, keyed by regime name. Each value: {'status': 'GO'|'NO_GO'|'INSUFFICIENT_DATA', 'expectancy': str, 'profit_factor': str, 'sharpe_ratio': str|None, 'max_drawdown_pct': str, 'trade_count': int, 'backtest_run_id': str, 'evaluated_at': iso8601 str}",
            ),
        ),
    ]