# Generated by Django 5.0.14 on 2026-08-19 07:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0003_ruleconfig_validated_regimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC datetime when this record was created.'),
        ),
        migrations.AlterField(
            model_name='ruleconfig',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='UTC datetime when this record was soft-deleted.', null=True),
        ),
        migrations.AlterField(
            model_name='ruleconfig',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4, not auto-increment).', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ruleconfig',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='True when this record has been soft-deleted.'),
        ),
        migrations.AlterField(
            model_name='ruleconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='UTC datetime when this record was last modified.'),
        ),
        migrations.AlterField(
            model_name='ruleexecution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC datetime when this record was created.'),
        ),
        migrations.AlterField(
            model_name='ruleexecution',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='UTC datetime when this record was soft-deleted.', null=True),
        ),
        migrations.AlterField(
            model_name='ruleexecution',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4, not auto-increment).', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ruleexecution',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='True when this record has been soft-deleted.'),
        ),
        migrations.AlterField(
            model_name='ruleexecution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='UTC datetime when this record was last modified.'),
        ),
    ]
