# Generated by Django 5.2.16 on 2026-08-12 11:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DriftRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4, not auto-increment).",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="UTC datetime when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="UTC datetime when this record was last modified.",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True when this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="UTC datetime when this record was soft-deleted.",
                        null=True,
                    ),
                ),
                ("account_id", models.UUIDField(db_index=True)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[("POSITION", "POSITION"), ("ORDER", "ORDER")],
                        max_length=16,
                    ),
                ),
                ("entity_key", models.CharField(max_length=128)),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("MATCHED", "MATCHED"),
                            ("MISSING_IN_READ_MODEL", "MISSING_IN_READ_MODEL"),
                            ("STALE_IN_READ_MODEL", "STALE_IN_READ_MODEL"),
                            ("ORPHANED_IN_READ_MODEL", "ORPHANED_IN_READ_MODEL"),
                            ("COMPARISON_ERROR", "COMPARISON_ERROR"),
                        ],
                        max_length=32,
                    ),
                ),
                ("expected_snapshot", models.JSONField(blank=True, default=dict)),
                ("actual_snapshot", models.JSONField(blank=True, default=dict)),
                ("auto_repaired", models.BooleanField(default=False)),
                ("detected_at", models.DateTimeField(db_index=True)),
                ("repaired_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Drift Record",
                "verbose_name_plural": "Drift Records",
                "db_table": "portfolio_reconciliation_driftrecord",
                "indexes": [
                    models.Index(
                        fields=["account_id", "classification", "-detected_at"],
                        name="portfolio_r_account_8b52f6_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "-detected_at"],
                        name="portfolio_r_entity__c031d4_idx",
                    ),
                ],
            },
        ),
    ]
