# Generated by Django 6.0.7 on 2026-07-26 12:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4).', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='Email address used for authentication.', max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('TRADER', 'Trader'), ('READ_ONLY', 'Read Only')], db_index=True, default='TRADER', help_text='User role — determines permissions across the platform.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user account is active.')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether this user can access the Django admin.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC datetime when this account was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC datetime when this account was last modified.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
    ]
