# Generated by Django 6.0.7 on 2026-08-02 13:41

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KillSwitchState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4, not auto-increment).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC datetime when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC datetime when this record was last modified.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True when this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='UTC datetime when this record was soft-deleted.', null=True)),
                ('scope', models.CharField(db_index=True, max_length=20)),
                ('symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField()),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.CharField(default='system', max_length=255)),
                ('reason', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Kill Switch State',
                'verbose_name_plural': 'Kill Switch States',
                'db_table': 'risk_management_killswitchstate',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('scope', 'symbol'), name='uq_killswitch_active_scope_symbol')],
            },
        ),
        migrations.CreateModel(
            name='RiskDecisionExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4, not auto-increment).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC datetime when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC datetime when this record was last modified.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True when this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='UTC datetime when this record was soft-deleted.', null=True)),
                ('analysis_event_id', models.UUIDField()),
                ('rule_id', models.CharField(db_index=True, max_length=255)),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('event_type', models.CharField(default='', max_length=50)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('rejection_code', models.CharField(blank=True, max_length=60, null=True)),
                ('entry_price', models.CharField(blank=True, max_length=40, null=True)),
                ('stop_loss', models.CharField(blank=True, max_length=40, null=True)),
                ('position_size', models.IntegerField(default=0)),
                ('risk_amount', models.CharField(blank=True, max_length=40, null=True)),
                ('risk_pct_of_capital', models.CharField(blank=True, max_length=40, null=True)),
                ('risk_reward_ratio', models.CharField(blank=True, max_length=40, null=True)),
                ('trigger_data', models.JSONField(blank=True, default=dict)),
                ('reason_message', models.TextField(blank=True, default='')),
                ('portfolio_gateway_impl', models.CharField(default='stub', max_length=60)),
                ('published_event_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Risk Decision Execution',
                'verbose_name_plural': 'Risk Decision Executions',
                'db_table': 'risk_management_riskdecisionexecution',
                'constraints': [models.UniqueConstraint(fields=('analysis_event_id', 'rule_id'), name='uq_riskdecision_event_rule')],
            },
        ),
    ]
