# Generated by Django 5.0.14 on 2026-08-22 08:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DriftAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4, not auto-increment).",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="UTC datetime when this record was last modified.",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True when this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="UTC datetime when this record was soft-deleted.",
                        null=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("sign_flip", "sign_flip"),
                            ("threshold", "threshold"),
                        ],
                        max_length=20,
                    ),
                ),
                ("window_trades", models.IntegerField()),
                (
                    "live_expectancy",
                    models.DecimalField(decimal_places=6, max_digits=18),
                ),
                ("live_win_rate", models.DecimalField(decimal_places=4, max_digits=7)),
                (
                    "baseline_expectancy",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                ("message", models.CharField(max_length=500)),
                ("notified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ObservedRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4, not auto-increment).",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="UTC datetime when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="UTC datetime when this record was last modified.",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True when this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="UTC datetime when this record was soft-deleted.",
                        null=True,
                    ),
                ),
                ("rule_id", models.CharField(max_length=100)),
                ("regime", models.CharField(max_length=50)),
                ("symbol", models.CharField(blank=True, default="", max_length=50)),
                (
                    "baseline_expectancy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Backtest expectancy per trade at realistic costs, from EDGE_VALIDATION_REPORT_V2.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, default="", max_length=280)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["rule_id", "regime", "enabled"],
                        name="live_drift__rule_id_f93222_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="observedrule",
            constraint=models.UniqueConstraint(
                fields=("rule_id", "regime", "symbol"), name="uniq_observed_rule_scope"
            ),
        ),
        migrations.AddField(
            model_name="driftalert",
            name="observed_rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="live_drift.observedrule",
            ),
        ),
        migrations.AddIndex(
            model_name="driftalert",
            index=models.Index(
                fields=["observed_rule", "created_at"],
                name="live_drift__observe_4e3463_idx",
            ),
        ),
    ]
