# Generated by Django 6.0.7 on 2026-07-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField()),
                ('event_type', models.CharField(max_length=255)),
                ('consumer_group', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('failure_reason', models.TextField()),
                ('attempts', models.IntegerField()),
                ('failed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dead Letter Event',
                'verbose_name_plural': 'Dead Letter Events',
                'db_table': 'eventbus_deadletterevent',
                'indexes': [models.Index(fields=['event_type', 'failed_at'], name='eventbus_de_event_t_370076_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField()),
                ('consumer_group', models.CharField(max_length=255)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Processed Event',
                'verbose_name_plural': 'Processed Events',
                'db_table': 'eventbus_processedevent',
                'indexes': [models.Index(fields=['event_id', 'consumer_group'], name='eventbus_pr_event_i_22c749_idx')],
                'constraints': [models.UniqueConstraint(fields=('event_id', 'consumer_group'), name='uq_processed_event_consumer')],
            },
        ),
        migrations.CreateModel(
            name='StoredEvent',
            fields=[
                ('event_id', models.UUIDField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=255)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('payload', models.JSONField()),
                ('version', models.IntegerField()),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('causation_id', models.UUIDField(blank=True, null=True)),
                ('mirrored_to_stream', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Stored Event',
                'verbose_name_plural': 'Stored Events',
                'db_table': 'eventbus_storedevent',
                'indexes': [models.Index(fields=['correlation_id', 'occurred_at'], name='eventbus_st_correla_660b47_idx'), models.Index(fields=['event_type', 'occurred_at'], name='eventbus_st_event_t_87d1e2_idx')],
            },
        ),
    ]
