# Generated by Django 5.0.14 on 2026-09-25 14:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backtesting", "0003_backtestrun_strategy"),
        ("strategy_registry", "0002_alter_tradingstrategy_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategySymbolAffinity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID4, not auto-increment).",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="UTC datetime when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="UTC datetime when this record was last modified.",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True when this record has been soft-deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="UTC datetime when this record was soft-deleted.",
                        null=True,
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=100)),
                (
                    "rank",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="1 = best-performing strategy for this symbol",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                (
                    "expectancy",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "profit_factor",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "sharpe_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "max_drawdown_pct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("trade_count", models.IntegerField(default=0)),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_run",
                    models.ForeignKey(
                        blank=True,
                        help_text="Completed backtest run the ranking was computed from.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="backtesting.backtestrun",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symbol_affinities",
                        to="strategy_registry.tradingstrategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Strategy-Symbol Affinity",
                "verbose_name_plural": "Strategy-Symbol Affinities",
                "ordering": ["symbol", "rank"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "rank"], name="idx_strategy_symbol_affinity"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="strategysymbolaffinity",
            constraint=models.UniqueConstraint(
                fields=("strategy", "symbol"), name="uniq_strategy_symbol_affinity"
            ),
        ),
    ]
