# Generated by Django 6.0.7 on 2026-07-27 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlogentry',
            new_name='audit_log_a_target__6b7684_idx',
            old_name='audit_log_a_target__d5ccad_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlogentry',
            new_name='audit_log_a_occurre_1b9960_idx',
            old_name='audit_log_a_occurre_070e7a_idx',
        ),
    ]
