# Generated by Django 6.0.7 on 2026-07-27 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='journal_jou_account_79ed10_idx',
            old_name='journal_jou_account_3bf73a_idx',
        ),
        migrations.RenameIndex(
            model_name='journaleventlog',
            new_name='journal_eve_event_i_a1946c_idx',
            old_name='journal_even_event_i_d8e7ed_idx',
        ),
    ]
