# Generated by Django 6.0.7 on 2026-08-11 13:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineHealthSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4, not auto-increment).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC datetime when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC datetime when this record was last modified.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True when this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='UTC datetime when this record was soft-deleted.', null=True)),
                ('evaluated_at', models.DateTimeField(db_index=True)),
                ('overall_status', models.CharField(choices=[('HEALTHY', 'HEALTHY'), ('DEGRADED', 'DEGRADED'), ('STALLED', 'STALLED')], max_length=16)),
                ('stage_statuses', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Pipeline Health Snapshot',
                'verbose_name_plural': 'Pipeline Health Snapshots',
                'db_table': 'pipeline_health_pipelinehealthsnapshot',
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='StageHeartbeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4, not auto-increment).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC datetime when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC datetime when this record was last modified.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True when this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='UTC datetime when this record was soft-deleted.', null=True)),
                ('stage', models.CharField(choices=[('MARKET_DATA', 'MARKET_DATA'), ('TECHNICAL_ANALYSIS', 'TECHNICAL_ANALYSIS'), ('INTELLIGENCE', 'INTELLIGENCE'), ('RULE_ENGINE', 'RULE_ENGINE'), ('EXECUTION', 'EXECUTION')], max_length=32)),
                ('symbol_scope', models.CharField(max_length=32)),
                ('last_event_at', models.DateTimeField()),
                ('last_event_id', models.UUIDField()),
                ('last_correlation_id', models.UUIDField()),
            ],
            options={
                'verbose_name': 'Stage Heartbeat',
                'verbose_name_plural': 'Stage Heartbeats',
                'db_table': 'pipeline_health_stageheartbeat',
                'indexes': [models.Index(fields=['stage', 'last_event_at'], name='idx_stage_heartbeat_stage_event')],
                'constraints': [models.UniqueConstraint(fields=('stage', 'symbol_scope'), name='uq_stage_heartbeat_stage_scope')],
            },
        ),
    ]
