# Generated by Django 5.0.14 on 2026-08-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_health', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stageheartbeat',
            new_name='idx_stage_heartbeat_evt',
            old_name='idx_stage_heartbeat_stage_event',
        ),
    ]
