# Generated by Django 6.0.7 on 2026-08-03 18:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawWebhookEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this webhook event.', primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('tradingview', 'TradingView'), ('chartink', 'Chartink')], db_index=True, help_text='Origin of the webhook payload.', max_length=50)),
                ('raw_body', models.JSONField(help_text='The raw webhook payload as a JSON blob.')),
                ('headers', models.JSONField(blank=True, default=dict, help_text='HTTP headers from the original request.')),
                ('signature_valid', models.BooleanField(default=False, help_text='Whether the request signature was verified successfully.')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC datetime when this webhook was received.')),
                ('processed', models.BooleanField(db_index=True, default=False, help_text='Whether this event has been published downstream.')),
            ],
            options={
                'verbose_name': 'Raw Webhook Event',
                'verbose_name_plural': 'Raw Webhook Events',
                'db_table': 'ingestion_raw_webhook_event',
                'indexes': [models.Index(fields=['source', 'received_at'], name='idx_ingestion_source_received'), models.Index(fields=['processed', 'received_at'], name='idx_ingestion_processed')],
            },
        ),
    ]
