# Generated by Django 6.0.7 on 2026-07-31 17:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricalFeatureVector",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this historical feature vector.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        db_index=True,
                        help_text="Trading symbol (e.g. RELIANCE).",
                        max_length=50,
                    ),
                ),
                (
                    "as_of",
                    models.DateField(
                        db_index=True, help_text="Trading session date (UTC)."
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Serialised FeatureVector: Decimal values stored as strings.",
                    ),
                ),
                (
                    "subsequent_price_change_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Actual % price change over the following session (outcome).",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "subsequent_window_hours",
                    models.IntegerField(
                        default=24,
                        help_text="Outcome window in hours (default: next trading day).",
                    ),
                ),
                (
                    "data_sufficiency_note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable note about data coverage for this session.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historical Feature Vector",
                "verbose_name_plural": "Historical Feature Vectors",
                "db_table": "pattern_engine_historicalfeaturevector",
                "ordering": ["-as_of"],
                "indexes": [
                    models.Index(fields=["symbol", "as_of"], name="idx_pe_symbol_asof")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("symbol", "as_of"), name="uq_pattern_engine_symbol_asof"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PatternAnalysisRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this analysis run.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        db_index=True,
                        help_text="Trading symbol (e.g. RELIANCE).",
                        max_length=50,
                    ),
                ),
                (
                    "as_of",
                    models.DateTimeField(
                        db_index=True, help_text="UTC datetime of the analysed session."
                    ),
                ),
                (
                    "top_analogue_summary",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human-readable summary of the top matching analogue.",
                    ),
                ),
                (
                    "confidence_contribution",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Deterministic confidence contribution in [0, 1].",
                        max_digits=5,
                    ),
                ),
                (
                    "historical_recommendation_accuracy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Trader Memory win rate for the symbol (optional enrichment).",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "matched_patterns",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Serialised list of MatchedPattern entries.",
                    ),
                ),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Serialised list of EvidenceItem entries.",
                    ),
                ),
                (
                    "data_sufficiency_note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. 'only 40 days of history available'.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pattern Analysis Run",
                "verbose_name_plural": "Pattern Analysis Runs",
                "db_table": "pattern_engine_patternanalysisrun",
                "ordering": ["-as_of"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "as_of"], name="idx_pe_run_symbol_asof"
                    )
                ],
            },
        ),
    ]
