# Generated by Django 5.0.14 on 2026-08-19 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='signal',
            new_name='signals_eng_instrum_d7df11_idx',
            old_name='signals_engine_signal_sym_created',
        ),
        migrations.RenameIndex(
            model_name='signal',
            new_name='signals_eng_source__c8bafd_idx',
            old_name='signals_engine_signal_src_created',
        ),
    ]
