# Generated by Django 5.0.14 on 2026-08-19 07:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader_memory', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='memoryentry',
            new_name='trader_memo_recomme_3b3392_idx',
            old_name='trader_memo_recomme_6eb1be_idx',
        ),
        migrations.AlterField(
            model_name='memoryentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC datetime when this record was created.'),
        ),
        migrations.AlterField(
            model_name='memoryentry',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='UTC datetime when this record was soft-deleted.', null=True),
        ),
        migrations.AlterField(
            model_name='memoryentry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4, not auto-increment).', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='memoryentry',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='True when this record has been soft-deleted.'),
        ),
        migrations.AlterField(
            model_name='memoryentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='UTC datetime when this record was last modified.'),
        ),
        migrations.AlterField(
            model_name='memoryprojection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC datetime when this record was created.'),
        ),
        migrations.AlterField(
            model_name='memoryprojection',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='UTC datetime when this record was soft-deleted.', null=True),
        ),
        migrations.AlterField(
            model_name='memoryprojection',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4, not auto-increment).', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='memoryprojection',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='True when this record has been soft-deleted.'),
        ),
        migrations.AlterField(
            model_name='memoryprojection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='UTC datetime when this record was last modified.'),
        ),
    ]
