# Generated by Django 5.0.14 on 2026-08-19 10:49

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader_memory', '0002_rename_trader_memo_recomme_6eb1be_idx_trader_memo_recomme_3b3392_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationDriftRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4, not auto-increment).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC datetime when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC datetime when this record was last modified.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True when this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='UTC datetime when this record was soft-deleted.', null=True)),
                ('rule_id', models.CharField(db_index=True, max_length=255)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('n_trades', models.IntegerField()),
                ('live_win_rate', models.DecimalField(decimal_places=6, max_digits=8)),
                ('expected_win_rate', models.DecimalField(decimal_places=6, max_digits=8)),
                ('p_value', models.DecimalField(decimal_places=8, max_digits=10)),
                ('drifted', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Calibration Drift Record',
                'verbose_name_plural': 'Calibration Drift Records',
                'db_table': 'trader_memory_calibrationdriftrecord',
                'indexes': [models.Index(fields=['rule_id', 'window_start'], name='trader_memo_rule_id_bbdbea_idx')],
            },
        ),
    ]
